core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import *

urlpatterns = [
    path('', index, name="index"), # PAGINA DE INICIO
    path('index/', index, name="index"),
    path('admin/', admin, name="admin"),
    path('medico/', medico, name="medico"),
    path('paciente/', paciente, name="paciente"),
    path('quienessomos/' , quienessomos, name="quienessomos"),
    path('login/', user_login, name='login'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
    #CRUD
    path('registrar_paciente/', registrar_paciente, name='registrar_paciente'),
    path('listar_pacientes/', listar_pacientes, name='listar_pacientes'),
    path('editar_paciente/<id>/', editar_paciente, name='editar_paciente'),
    path('buscar_paciente/', buscar_paciente, name='buscar_paciente'),
    path('registrar_atencion/<id>/', registrar_atencion, name='registrar_atencion'),
    path('atencion_exito/', atencion_exito, name='atencion_exito'),
    path('detalle_atencion/<id>/', detalle_atencion, name='detalle_atencion'),
    path('listar_fichasmedicas/', listar_fichasmedicas, name='listar_fichasmedicas'),
    path('ficha_paciente/<id>/', ficha_paciente, name='ficha_paciente'),
    path('registro_exitoso/', registro_exitoso, name='registro_exitoso'),
    path('soporte/', soporte, name='soporte'),
]

medidata/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

#Configuracion del admin
admin.site.site_title = "Medidata"
admin.site.site_header = "Administración de Medidata"
admin.site.index_title = "Medidata Administración"

core/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.contrib import admin

# Create your models here.

class TipoMedico(models.Model):
    descripcion = models.CharField(max_length=50)

    def __str__(self):
        return self.descripcion

class Medico(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='medico_profile', null=True, blank=True)
    especialidad = models.ForeignKey(TipoMedico, on_delete=models.CASCADE)    

    def __str__(self):
        return f"{self.user.get_full_name()} - {self.especialidad.descripcion}"

class Paciente(models.Model):
    GENERO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('O', 'Otro'),
    ]

    rut = models.CharField(max_length = 12, blank=False, unique= True)
    nombre = models.CharField(max_length = 40, blank=False)
    apellido = models.CharField(max_length = 40, blank=False)
    fecha_nacimiento = models.DateField(blank=False, null=False)
    genero = models.CharField(max_length=1, choices=GENERO_CHOICES, blank=False)
    telefono = models.CharField(max_length = 12, blank=False) 
    correo = models.EmailField(blank=False)

    def __str__(self):
        return f"{self.rut}"

class FichaMedica(models.Model):
    paciente = models.OneToOneField(Paciente, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.id}"

class Atencion(models.Model):
    ficha_medica = models.ForeignKey(FichaMedica, on_delete=models.CASCADE)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    medico = models.ForeignKey(User, on_delete=models.CASCADE)
    especialidad = models.ForeignKey(TipoMedico, on_delete=models.SET_NULL, null=True, blank=True)  # Nueva relación a TipoMedico
    fecha_atencion = models.DateField()
    anamesis = models.TextField()
    medicamentos_recetados = models.TextField(blank=True, null=True)
    examenes_indicados = models.TextField(blank=True, null=True)
    diagnostico = models.TextField()

    def __str__(self):
        return f"Atención de {self.paciente} por {self.medico} el {self.fecha_atencion}"

@receiver(post_save, sender=Paciente)
def crear_ficha_medica(sender, instance, created, **kwargs):
    if created:
        FichaMedica.objects.create(paciente=instance)

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import Group, User
from .forms import * 
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
# Create your views here.


def index(request):
    return render(request, 'core/index.html')

def base(request):
    return render(request, 'core/base.html')

def admin(request):
    return render(request, 'core/admin.html')

@login_required
def medico(request):
    return render(request, 'core/medico.html', {'nombre_usuario': request.user.get_full_name() or request.user.username})

@login_required
def paciente(request):
    return render(request, 'core/paciente.html', {'nombre_usuario': request.user.get_full_name() or request.user.username})

def quienessomos(request):
    return render(request, 'core/quienessomos.html')

def user_login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                if user.groups.filter(name='Administradores').exists(): #si el usuario está en el grupo administradores
                    return redirect('admin')  # Redirige a la URL del administrador
                elif user.groups.filter(name='Medicos').exists():
                    return redirect('medico')  # Redirige a la URL del médico
                elif user.groups.filter(name='Pacientes').exists():
                    return redirect('paciente')  # Redirige a la URL del paciente
    else:
        form = CustomAuthenticationForm()
    return render(request, 'core/login.html', {'form': form})

def admin(request):
    return render(request, 'core/admin.html')

#CRUD

@login_required

def registrar_paciente(request):
    if request.method == 'POST':
        formulario = PacienteForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            #messages.success(request, "Paciente registrado correctamente")
            return redirect('registro_exitoso')  # Redirige a la vista de éxito
        else:
            messages.error(request, "Error al registrar el paciente. Por favor, verifica los datos ingresados.")
    else:
        formulario = PacienteForm()
    return render(request, 'core/paciente/registrar_paciente.html', {'form': formulario})
            


@login_required
def listar_pacientes(request):
    listaPacientes = Paciente.objects.all()
    paginator = Paginator(listaPacientes, 10)

    # Obtén el número de página desde la solicitud GET
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)  # Obtener la página actual

    datos = {'page_obj': page_obj}  # Pasar la página al template

    return render(request, 'core/paciente/listar_pacientes.html',datos)


@login_required
def editar_paciente(request,id):
    paciente = Paciente.objects.get(id=id)
    datos = { 'form' : EditarPacienteForm (instance = paciente), 'paciente': paciente }

    if request.method == 'POST':
        formulario = EditarPacienteForm(data = request.POST, instance = paciente)
        if formulario.is_valid():
            formulario.save();
            messages.success(request, "Paciente modificado correctamente")
            datos['form'] = formulario

    return render(request, 'core/paciente/editar_paciente.html',datos)


@login_required
def registrar_atencion(request, id):
    paciente = get_object_or_404(Paciente, id=id)
    medico = request.user
    ficha_medica = FichaMedica.objects.filter(paciente=paciente).first()
    especialidad = medico.medico_profile.especialidad.descripcion if hasattr(medico, 'medico_profile') else 'Sin especialidad'
    datos = {'form': AtencionForm(initial={
        'paciente': paciente.rut,
        'ficha_medica': ficha_medica.id if ficha_medica else None,
        'medico': medico.get_full_name() or medico.username,  # Utilizar el nombre completo del usuario
        'fecha_atencion': date.today(),  # Inicializar la fecha de atención
        'especialidad': especialidad
        }),
        'especialidad': especialidad  # Agregar la especialidad al contexto para la plantilla
    }
    previsualizar = False

    if request.method == 'POST':
        formulario = AtencionForm(data=request.POST)
        if 'preview' in request.POST:
            if formulario.is_valid():
                previsualizar = True
                datos['form'] = formulario
                datos['previsualizar'] = True
        elif 'confirm' in request.POST:
            if formulario.is_valid():
                atencion = formulario.save(commit=False)
                atencion.medico = medico  # Asignar la instancia del Medico (User)
                atencion.paciente = paciente  # Asignar la instancia del Paciente
                atencion.ficha_medica = ficha_medica  # Asociar FichaMedica
                atencion.fecha_atencion = date.today()  # Asignar la fecha de atención
                atencion.save()
                #messages.success(request, "Atención registrada correctamente!")
                return redirect('atencion_exito')
        elif 'edit' in request.POST:
            # El caso 'edit' puede simplemente permitir al usuario editar de nuevo
            datos['form'] = formulario
            messages.info(request, "Edite la información antes de confirmar.")

    return render(request, 'core/atencion/registrar_atencion.html', {
        'form': datos['form'],
        'previsualizar': previsualizar,
        'msj': datos.get('msj', None),
        'paciente': paciente,
        'ficha_medica': ficha_medica,
        'medico': medico.get_full_name() or medico.username,
        'especialidad': especialidad  # Pasar la especialidad al contexto
    })

def atencion_exito(request):
    return render(request, 'core/atencion/atencion_exito.html')


from django.core.paginator import Paginator
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def listar_fichasmedicas(request):
    # Obtener todas las fichas médicas con el uso de select_related para optimizar consultas
    fichas_medicas = FichaMedica.objects.select_related('paciente').all()

    # Paginación: Mostrar 10 fichas por página
    paginator = Paginator(fichas_medicas, 10)  # Cambia el 10 al número deseado de fichas por página
    page_number = request.GET.get('page')  # Obtener el número de página de los parámetros de la URL
    page_obj = paginator.get_page(page_number)  # Obtener la página correspondiente

    return render(request, 'core/ficha_medica/listar_fichasmedicas.html', {
        'page_obj': page_obj,  # Pasar la página actual al contexto
    })



def ficha_paciente(request, id):
    ficha = get_object_or_404(FichaMedica, id=id)
    atenciones = Atencion.objects.filter(ficha_medica=ficha)

    return render(request, 'core/ficha_medica/ficha_paciente.html', {
    'ficha': ficha,
    'atenciones': atenciones,
    })

@login_required
def detalle_atencion(request, id):
    atencion = get_object_or_404(Atencion, id=id)
    ficha_medica = atencion.ficha_medica  # Obtener la ficha médica asociada a la atención
    medico_profile = getattr(atencion.medico, 'medico_profile', None)
    especialidad = medico_profile.especialidad.descripcion if medico_profile else 'Sin especialidad'

    return render(request, 'core/atencion/detalle_atencion.html', {
        'atencion': atencion,
        'ficha_medica': ficha_medica,
        'especialidad': especialidad
    })

@login_required
def registro_exitoso(request):
    return render(request, 'core/paciente/registro_exitoso.html')

@login_required
def buscar_paciente(request):
    form = BuscarPacienteForm()
    paciente = None

    if request.method == 'POST':
        form = BuscarPacienteForm(request.POST)
        if form.is_valid():
            rut_formateado = form.cleaned_data['rut']
            try:
                paciente = Paciente.objects.get(rut=rut_formateado)
            except Paciente.DoesNotExist:
                paciente = None

    return render(request, 'core/paciente/buscar_paciente.html', {
        'form': form,
        'paciente': paciente,
    })

@login_required
def soporte(request):
    return render(request, 'core/soporte.html')

core/templates/core/paciente/buscar_paciente.html
{% extends 'core/base.html' %}
{% block principal %}

<div class="d-flex flex-column min-vh-100">
    <div class="mt-3 text-center">
        <h3>Buscar Paciente por RUT</h3>
    </div>
    <div class="row">
        <div class="col-8 offset-2">
            <form method="POST" class="mt-4">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="text-center">
                    <button type="submit" class="btn btn-success">Buscar</button>
                </div>
            </form>
            {% if paciente %}
                <div class="mt-5 container text-center">
                    <h4>Paciente Encontrado</h4>
                    <p><strong>RUT:</strong> {{ paciente.rut }}</p>
                    <p><strong>Nombre:</strong> {{ paciente.nombre }} {{ paciente.apellido }}</p>
                    <p><strong>Fecha de Nacimiento:</strong> {{ paciente.fecha_nacimiento }}</p>
                    <p><strong>Género:</strong> {{ paciente.get_genero_display }}</p>
                    <p><strong>Teléfono:</strong> {{ paciente.telefono }}</p>
                    <p><strong>Correo:</strong> {{ paciente.correo }}</p>
                    <a href="{% url 'editar_paciente' paciente.id %}" class="btn btn-warning">Editar Paciente</a>
                    <a href="{% url 'registrar_atencion' paciente.id %}" class="btn btn-primary"">Agregar Atención</a>
                    <a href="{% url 'ficha_paciente' paciente.id %}" class="btn btn-info">Ver Ficha Paciente</a>
                </div>
            {% elif paciente is not none %}
                <div class="mt-5 alert alert-warning text-center">
                    No se encontró ningún paciente con el RUT ingresado.
                </div>
            {% endif %}
            <div class="text-center mt-5">
                <a class="btn btn-success" href="{% url 'listar_pacientes' %}">Volver a Listado de Pacientes</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/paciente/editar_paciente.html
{% extends 'core/base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block principal %}

<div class="container">

    <div class="row">
        <div class="col-8 offset-2">
            <div class="mt-3">
                {% if messages %}
                <div>
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="alert alert-info mt-5" role="alert">
                <h5>Editar paciente {{ paciente.nombre }} {{ paciente.apellido }}</h5>
                <p>Rut: {{ paciente.rut }} </p>
            </div>
            <div class="card">
                <div class="card-body p-5">
                    <div class="alert alert-warning role="alert">
                        <p>Nota: usted no tiene permisos para editar el rut del paciente.</p>
                    </div>
                    <form method="POST">
                    {% csrf_token %}

                    {% bootstrap_form form %}
                    <div class="text-center">
                        <button class="btn btn-success" type="submit">Modificar</button>
                    </div>
                    </form>
                <a href="{% url 'listar_pacientes' %}" class="btn btn-warning">Volver</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

core/templates/core/paciente/listar_pacientes.html
{% extends 'core/base.html' %}
{% load static %}

{% block principal %}
<div class="mt-5 container">
    <div class="d-flex justify-content-end">
        <a class="btn btn-danger" href="{% url 'buscar_paciente' %}">Buscar Paciente por Rut</a>
    </div>
    <div class="mt-5 container text-center">
        <h3>Listado de pacientes registrados en el centro médico</h3>
    </div>
    <table class="mt-5 table">
    <thead>
        <tr>
            <th scope="col">Rut</th>
            <th scope="col">Nombre</th>
            <th scope="col">Apellido</th>
            <th scope="col">Fecha Nacimiento</th>
            <th scope="col">Genero</th>
            <th scope="col">Telefono</th>
            <th scope="col">Correo</th>
            <th scope="col">Opciones</th>
        </tr>
    </thead>
    <tbody>
        {% for aux in page_obj %}
            <tr>
                <th scope="row">{{ aux.rut }}</th>
                <td>{{ aux.nombre }}</td>
                <td>{{ aux.apellido }}</td>
                <td>{{ aux.fecha_nacimiento }}</td>
                <td>{{ aux.genero }}</td>
                <td>{{ aux.telefono }}</td>
                <td>{{ aux.correo }}</td>
                <td>
                    <a href="{% url 'registrar_atencion' aux.id %}" class="btn btn-info">Agregar Atención</a>
                    <a href="{% url 'editar_paciente' aux.id %}" class="btn btn-warning">Editar</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
    </table>
    <a class="btn btn-success" href="{% url 'medico' %}">Volver a Inico</a>
</div>

<!-- Bloque de paginación -->
<nav aria-label="Page navigation" class="mt-4">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            <li class="page-item {% if page_obj.number == num %}active{% endif %}">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</nav>
{% endblock %}


<!-- el codigo de abajo hace que la pagina sea responsiva creo... revisalo -->

<!--

<div class="mt-5 container">
    <div class="mt-5 container text-center">
        <h3>Listado de pacientes registrados en el centro médico</h3>
    </div>
    <div class="table-responsive mt-5">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Rut</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Apellido</th>
                    <th scope="col">Fecha Nacimiento</th>
                    <th scope="col">Genero</th>
                    <th scope="col">Telefono</th>
                    <th scope="col">Correo</th>
                    <th scope="col">Opciones</th>
                </tr>
            </thead>
            <tbody>
                {% for aux in lista %}
                    <tr>
                        <th scope="row">{{ aux.rut}}</th>
                        <td>{{ aux.nombre}}</td>
                        <td>{{ aux.apellido}}</td>
                        <td>{{ aux.fecha_nacimiento}}</td>
                        <td>{{ aux.genero}}</td>
                        <td>{{ aux.telefono}}</td>
                        <td>{{ aux.correo}}</td>
                        <td>
                            <a href="{% url 'registrar_atencion' aux.id %}" class="btn btn-info">Agregar Atención</a>
                            <a href="{% url 'editar_paciente' aux.id %}" class="btn btn-warning">Editar</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <a class="btn btn-success" href="{% url 'medico' %}">Volver a Inico</a>
</div>

-->

core/templates/core/paciente/registrar_paciente.html
{% extends 'core/base.html' %}
{% load static %}

{% block principal %}
<div class="mt-5 container">
    {% if messages %}
        <div>
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <div class="row">
        <div class="col-8 offset-2">
            <div class="card">
                <div class="card-header text-center">
                    <div class="card-title">
                        <h3>Registro de Pacientes</h3>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="text-center">
                            <button class="mt-2 btn btn-success" type="submit">Agregar</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer p-3">
                    <a class="mt-2 btn btn-warning" href="{% url 'medico' %}">Volver</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/paciente/registro_exitoso.html
{% extends 'core/base.html' %}
{% load static %}

{% block principal %}
<div class="mt-2 container min-vh-25 d-flex flex-column justify-content-center"></div>
    <div class="row flex-grow-1">
        <div class="col-8 offset-2">
            <div class="card">
                <div class="card-header text-center">
                    <div class="card-title">
                        <h3>Registro Exitoso</h3>
                    </div>
                </div>
                <div class="card-body text-center">
                    <p>El paciente ha sido registrado correctamente.</p>
                    <a class="btn btn-primary" href="{% url 'medico' %}">Volver</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}